name = "morning-routine"
main = "src/worker/index.ts"
compatibility_date = "2026-06-23"
tsconfig = "tsconfig.worker.json"

[assets]
directory = "./dist"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "morning-routine-db"
database_id = "8bb113d0-b98d-439d-b902-38b030b89b61"

[[kv_namespaces]]
binding = "SESSIONS"
id = "20a17b1d77374dfba94792d2266140b2"
