// Generates scripts/seed.sql from src/client/data/exercises.ts — the typed
// library is the source of truth; this keeps D1 in sync with it.
// Run via `npm run seed:gen` (or implicitly through seed:local / seed:remote).
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { LIBRARY } from '../src/client/data/exercises'
import type { Exercise, Phase } from '../src/shared/types'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(__dirname, 'seed.sql')

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function sqlNullableString(value: string | undefined): string {
  return value === undefined ? 'NULL' : sqlString(value)
}

function insertFor(ex: Exercise, sortOrder: number): string {
  const values = [
    sqlString(ex.id),
    sqlString(ex.phase),
    sqlString(ex.name),
    sqlString(ex.tag),
    String(ex.dur),
    sqlString(JSON.stringify(ex.tempo)),
    sqlString(JSON.stringify(ex.how)),
    sqlNullableString(ex.mistake),
    sqlNullableString(ex.quiet),
    sqlString(ex.equipment ?? 'none'),
    String(sortOrder),
  ]
  return `INSERT INTO exercises (id, phase, name, tag, base_dur, tempo_json, how_json, mistake, quiet, equipment, sort_order) VALUES (${values.join(', ')});`
}

const phases: Phase[] = ['warmup', 'circuit', 'cooldown']
const lines = ['-- Generated by scripts/seed-exercises.ts — do not edit by hand.', 'DELETE FROM exercises;']
let count = 0

for (const phase of phases) {
  LIBRARY[phase].forEach((ex, i) => {
    lines.push(insertFor(ex, i))
    count++
  })
}

writeFileSync(outFile, lines.join('\n') + '\n')
console.log(`Wrote ${count} exercises to ${outFile}`)
